mysite/cpp/urls.py
from django.urls import path
from . import views

app_name = 'cpp'
urlpatterns = [
    path(
        'resposta/<int:id_resposta>/avalia/', 
        views.AvaliaRespostaView.as_view(), name='avalia'
    ),
    path(
        'turma/<int:id_turma>/nova-avaliacao/',
        views.NovaAvaliacaoView.as_view(), name='nova-avaliacao'
    ),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cpp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/cpp/models.py
from django.db import models
from django.contrib.auth.models import User

## Classe Curso
##########################
class Curso(models.Model):
    NIVEL = [
        (1, "Técnico"),
        (2, "Superior de Tecnologia"),
        (3, "Engenharia")
    ]
    nome = models.CharField(max_length=60)
    descricao = models.CharField(max_length=100)
    nivel = models.IntegerField(choices=NIVEL, default=1)
    def __str__(self):
        return self.nome

## Classe Disciplina
###############################
class Disciplina(models.Model):
    nome = models.CharField(max_length=40)
    curso = models.ForeignKey(Curso, on_delete=models.CASCADE)
    def __str__(self):
        return self.nome

## Classe Professor
#############################
class Professor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.user.username

## Classe Aluno
##########################
class Aluno(models.Model):
    matricula = models.CharField(max_length=15)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.matricula

## Classe Turma
##########################
class Turma(models.Model):
    nome = models.CharField(max_length=30)
    ativa = models.BooleanField(default=True)
    disciplina = models.ForeignKey(Disciplina, on_delete=models.CASCADE)
    professor = models.ForeignKey(Professor, on_delete=models.CASCADE)
    alunos = models.ManyToManyField(Aluno)
    def __str__(self):
        return self.nome

## Classe Avaliação
##############################
class Avaliacao(models.Model):
    ESTAGIO = [
        (1, "Criada"),
        (2, "Em submissão"),
        (3, "Em correção"),
        (4, "Finalizada"),
    ]
    TIPO_CORRECAO = [
        (1, "Pelo professor"),
        (2, "Pelos pares"),
    ]
    titulo = models.CharField(max_length=30)
    enunciado = models.CharField(max_length=300)
    nota = models.IntegerField(default=100)
    data = models.DateField(auto_now_add=True)
    estagio = models.IntegerField(choices=ESTAGIO, default=1)
    correcao = models.IntegerField(choices=TIPO_CORRECAO, default=2)
    turma = models.ForeignKey(Turma,on_delete=models.CASCADE)
    def __str__(self):
        return self.titulo

## Classe Correção
#############################
class Correcao(models.Model):
    nota = models.IntegerField()
    comentarios = models.CharField(max_length=200)
    def __str__(self):
        return "Correcao ({})".format(self.id)

## Classe Correção Por Par
###############################
class CorrecaoPorPar(Correcao):
    aluno = models.ForeignKey(Aluno, models.CASCADE)
    def __str__(self):
        return "Correcao por par ({})".format(self.id)

## Classe Professor
#############################
class Resposta(models.Model):
    submissao = models.DateTimeField(auto_now_add=True)
    diagrama = models.ImageField(upload_to='respostas')
    observacao = models.CharField(max_length=200)
    avaliacao = models.ForeignKey(Avaliacao, on_delete=models.CASCADE)
    aluno = models.ForeignKey(Aluno, on_delete=models.CASCADE)
    correcao = models.OneToOneField(
        Correcao, on_delete=models.CASCADE, null=True, blank=True
    )
    def __str__(self):
        return "Resposta ({})".format(self.id)
    def set_correcao(self, correcao):
        self.correcao = correcao

mysite/cpp/views.py
from django.shortcuts import render, redirect
from django.views import View
from .services import ServicoResposta, ServicoCorrecao, ServicoTurma
from .models import Avaliacao

## Avalia Resposta View
###############################
class AvaliaRespostaView(View):
    def get(self, request, *args, **kwargs):
        srv = ServicoResposta()
        id_resposta = kwargs.get('id_resposta', '')
        obj = srv.recupera_resposta(id_resposta)
        contexto = {'resposta': obj}
        return render(request, 'cpp/avalia_resposta.html', contexto)

    def post(self, request, *args, **kwargs):
        srv = ServicoCorrecao()
        id_resposta = kwargs.get('id_resposta', '')
        #if request.user.is_authenticated and request.user.aluno:
        id_aluno = 1
        nota = request.POST.get('nota','')
        comentario = request.POST.get('comentario', '')
        id_aval = srv.salvar_correcao(id_resposta, id_aluno, nota, comentario)
        return redirect('/avaliacao/{}/'.format(id_aval))

## Nova Avaliação View
##############################
class NovaAvaliacaoView(View):
    def get(self, request, *args, **kwargs):
        srv = ServicoTurma()
        id_turma = kwargs.get('id_turma', '')
        turma = srv.get_turma(id_turma)
        contexto = {'turma': turma, "tipos": Avaliacao.TIPO_CORRECAO}
        # TODO: só será exibido o formulário se o professor logado estiver associado à turma
        return render(request, 'cpp/nova_avaliacao.html', contexto)

    def post(self, request, *args, **kwargs):
        srv = ServicoTurma()
        id_turma = kwargs.get('id_turma', '')
        turma = srv.get_turma(id_turma)
        # TODO: confirmar que o professor logado está associado a turma em questão
        if turma:
            titulo = request.POST.get('titulo', '')
            enunciado = request.POST.get('enunciado', '')
            max_nota = request.POST.get('nota', '')
            tipo_correcao = request.POST.get('correcao', '')
            if titulo and enunciado and max_nota and tipo_correcao:
                id_avaliacao = srv.adiciona_avaliacao(
                    turma, titulo, enunciado, max_nota, tipo_correcao
                )
                if id_avaliacao:
                    return redirect('/avaliacao/{}/'.format(id_avaliacao))

mysite/cpp/templates/cpp/avalia_resposta.html
<html>
    <head>
        <title>App CPP</title>
    </head>
    <body>
        <h1>Aplicação CorreçãoPorPar</h1>
        <h2>Avaliação da Resposta de um Aluno</h2>
        {% if user.is_authenticated %}
            <h3>Bem vindo, usuário {{ user.username }}</h3>
        {% endif %}
        <p>
            <u>Diagrama submetido por um colega</u>:<br/>
            <img src="{{ resposta.diagrama.url }}" alt="diagrama"/>
        </p>
        <p>
            <u>Observações</u>: {{ resposta.observacao }}
        </p>
        <hr/>
        <form method="post" action="{% url 'cpp:avalia' resposta.id %}">
            {% csrf_token %}
            <h3>Registre a sua avaliação:</h3>
            <p>Qual a sua nota para o diagrama (0-100):
            <input type="number" name="nota" required/></p>
            <p>Comentários:<br/>
            <textarea name="comentario" cols="60">Informe aqui os motivos para a nota atribuída...
            </textarea></p>
            <p><input type="submit" value="Registrar a Avaliação"/></p>
        </form>
    </body>
</html>

mysite/cpp/templates/cpp/nova_avaliacao.html
<html>
    <head>
        <title>App CPP</title>
    </head>
    <body>
        <h1>Aplicação CorreçãoPorPar</h1>
        <h2>Criação de uma Nova Avaliação para a turma {{ turma.nome }}</h2>
        <hr/>
        <form method="post" action="{% url 'cpp:nova-avaliacao' turma.id %}">
            {% csrf_token %}
            <p><u>Título</u>: <input type="text" name="titulo" size="54"/></p>
            <p><u>Enunciado</u>:<br/>
            <textarea cols="60" rows="3" name="enunciado"></textarea></p>
            <p><u>Nota (máxima, de 0 a 100)</u>: <input type="number" name="nota"/></p>
            <p><u>Tipo de correção</u>:
            <select name="correcao" id="tipo_correcao">
                {% for tipo in tipos %}
                <option value="{{ tipo.0 }}">{{ tipo.1 }}</option>
                {% endfor %}
            </select>
            </p>
            <input type="submit" value="Cadastrar a Avaliação"/>
        </form>
    </body>
</html>